/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Compiling and loading entity files generated by introspection, in-process —
 * shared by the unit conformance test and the echo integration tests.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import * as ts from "typescript";

/** Absolute path of the ORM's source entry, used as the generated import path. */
export const SRC_INDEX = resolve(__dirname, "../../src/index");

/** Writes `files` (name → source) into `dir` and returns their paths. */
export async function writeGenerated(
  dir: string,
  files: Map<string, string>,
): Promise<string[]> {
  await mkdir(dir, { recursive: true });
  const paths: string[] = [];
  for (const [name, code] of files) {
    const path = join(dir, name);
    await writeFile(path, code, "utf8");
    paths.push(path);
  }
  return paths;
}

/** Type checks the files under `strict`; returns their own diagnostics. */
export function typeCheck(files: string[]): string[] {
  const program = ts.createProgram(files, {
    strict: true,
    target: ts.ScriptTarget.ES2020,
    module: ts.ModuleKind.CommonJS,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    experimentalDecorators: true,
    emitDecoratorMetadata: true,
    esModuleInterop: true,
    skipLibCheck: true,
    noEmit: true,
    strictPropertyInitialization: false,
  });
  const own = new Set(files.map((f) => resolve(f)));
  return ts
    .getPreEmitDiagnostics(program)
    .filter((d) => d.file && own.has(resolve(d.file.fileName)))
    .map(
      (d) =>
        `${d.file?.fileName}: ${ts.flattenDiagnosticMessageText(d.messageText, " ")}`,
    );
}

/**
 * Compiles and evaluates the generated modules (relative imports resolved
 * among themselves, `SRC_INDEX` to the ORM source) and returns every exported
 * entity class.
 */
export function loadGenerated(files: string[]): any[] {
  const cache = new Map<string, any>();
  const load = (absolutePath: string): any => {
    const abs = resolve(absolutePath);
    if (cache.has(abs)) return cache.get(abs);
    const js = ts.transpileModule(readFileSync(abs, "utf8"), {
      compilerOptions: {
        module: ts.ModuleKind.CommonJS,
        target: ts.ScriptTarget.ES2020,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
        esModuleInterop: true,
      },
    }).outputText;

    const mod = { exports: {} as any };
    // Seeded before evaluation so a circular import resolves to the
    // partially-filled module instead of recursing forever.
    cache.set(abs, mod.exports);
    const requireShim = (id: string) => {
      if (id === SRC_INDEX) return require(SRC_INDEX);
      if (id.startsWith(".")) {
        return load(resolve(dirname(abs), id.replace(/\.js$/, ".ts")));
      }
      return require(id);
    };
    // eslint-disable-next-line no-new-func
    new Function("exports", "require", "module", "__filename", "__dirname", js)(
      mod.exports,
      requireShim,
      mod,
      abs,
      dirname(abs),
    );
    cache.set(abs, mod.exports);
    return mod.exports;
  };

  const entities: any[] = [];
  for (const file of files) {
    for (const value of Object.values(load(file))) {
      if (typeof value === "function") entities.push(value);
    }
  }
  return entities;
}
