import { ColumnType } from "../decorators/Column";
import { DbColumn, DbForeignKey, DbIndex } from "./EntityCodeBuilder";
import { IntrospectionDialect, IntrospectionTypeMapper } from "./TypeMapper";

/**
 * Dialect-neutral description of one entity, derived from introspected
 * table metadata.
 *
 * Both code emitters (decorator and code-first) consume this model, so the
 * two styles can never disagree about what a table means — they only differ
 * in how they spell it.
 */
export interface EntityModel {
  tableName: string;
  className: string;
  /** Stored columns and relations, in the order they should be emitted. */
  fields: EntityModelField[];
  /**
   * Class-level indexes, with columns already resolved to *property* names
   * (both the decorators and `defineEntity` resolve property keys back to DB
   * column names through the entity metadata).
   */
  classIndexes: ModelIndex[];
  /** Class names referenced by relations (FK targets), excluding self. */
  referencedClasses: string[];
}

export type EntityModelField = ModelColumnField | ModelRelationField;

/** A stored column. */
export interface ModelColumnField {
  kind: "column";
  propertyName: string;
  columnName: string;
  /** True when the DB column name differs from the property name. */
  needsNameOption: boolean;
  columnType: ColumnType;
  /** TypeScript type of the property, already widened for nullability. */
  tsType: string;
  nullable: boolean;
  primary: boolean;
  /** Primary key generated by the database (serial / auto_increment / rowid). */
  generated: boolean;
  /** A column that is both a FK and part of the PK — emitted as a plain PK column. */
  fkPrimary: boolean;
  length?: number;
  precision?: number;
  scale?: number;
  enumValues?: string[];
  /** Default value as a TypeScript literal source string (already quoted). */
  defaultLiteral?: string;
  /** Single-column, non-unique index on this column. */
  index: boolean;
  /** Timestamp role detected from the property name, type, and nullability. */
  timestamp?: "create" | "update" | "deletedAt";
  /**
   * Lossy-mapping notes emitted as comments above the field, so a mapping the
   * generator could not make faithful is visible in the generated file instead
   * of only showing up the next time the schema is synchronized.
   */
  warnings?: string[];
}

/** A `@ManyToOne` relation standing in for a foreign key column. */
export interface ModelRelationField {
  kind: "manyToOne";
  propertyName: string;
  targetClass: string;
  /** True when the FK points back at the same table. */
  selfReference: boolean;
  fkColumn: string;
  fkType: ColumnType;
  fkNullable: boolean;
  referencedColumn?: string;
  /** Lossy-mapping notes, emitted as comments above the relation. */
  warnings?: string[];
}

export interface ModelIndex {
  /** Property names (not DB column names). */
  columns: string[];
  name?: string;
  unique: boolean;
}

/**
 * Column types whose `(precision, scale)` is meaningful DDL rather than an
 * artifact of `information_schema` reporting binary precision for floats.
 *
 * PostgreSQL reports `numeric_precision = 53` for `double precision`; passing
 * that through produced `NUMERIC(53, …)` on the way back out, silently turning
 * a float8 column into a decimal one.
 */
const DECIMAL_SOURCE_TYPES = new Set([
  "numeric",
  "decimal",
  "dec",
  "fixed",
  "money",
]);

/**
 * Convert a snake_case table name to a PascalCase class name.
 * e.g. "user_profiles" -> "UserProfile"
 */
export function tableNameToClassName(tableName: string): string {
  // Remove trailing 's' for simple plurals (but not 'ss' like 'address')
  let singular = tableName;
  if (singular.endsWith("ies")) {
    singular = singular.slice(0, -3) + "y";
  } else if (
    singular.endsWith("ses") ||
    singular.endsWith("xes") ||
    singular.endsWith("zes")
  ) {
    singular = singular.slice(0, -2);
  } else if (singular.endsWith("s") && !singular.endsWith("ss")) {
    singular = singular.slice(0, -1);
  }

  return singular
    .split(/[_\-\s]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

/**
 * Convert PascalCase class name to kebab-case file name.
 * e.g. "UserProfile" -> "user-profile.entity.ts"
 */
export function classNameToFileName(className: string): string {
  const kebab = className
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
  return `${kebab}.entity.ts`;
}

/**
 * Convert a snake_case column name to a camelCase property name. Column names
 * without an underscore (already camelCase or PascalCase) only get their first
 * character lowercased, so `updatedAt` → `updatedAt`, `IsValid` → `isValid`.
 */
export function columnNameToPropertyName(columnName: string): string {
  if (!columnName.includes("_")) {
    return columnName.charAt(0).toLowerCase() + columnName.slice(1);
  }
  const parts = columnName.split("_");
  return parts
    .map((part, i) =>
      i === 0
        ? part.toLowerCase()
        : part.charAt(0).toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join("");
}

/**
 * Convert a FK column name to a relation property name. Strips both the
 * `_id` suffix (`post_id` → `post`) and the `id_` prefix (`id_ancestor` →
 * `ancestor`), falling through to plain camelCase otherwise.
 */
function fkToPropertyName(columnName: string): string {
  let name = columnName;
  if (/_id$/i.test(name)) {
    name = name.slice(0, -3);
  } else if (/^id_/i.test(name)) {
    name = name.slice(3);
  }
  return columnNameToPropertyName(name);
}

/**
 * Determine whether a PK column is auto-generated.
 * - PostgreSQL `is_identity = 'YES'` (PG 10+ identity columns)
 * - PostgreSQL legacy SERIAL (`serial`/`bigserial`, or a `nextval(…)` default)
 * - MySQL `EXTRA` containing `auto_increment`
 * - SQLite: a single `INTEGER PRIMARY KEY` is a rowid alias
 */
function isGeneratedPrimaryKey(
  col: DbColumn,
  context?: { dialect?: IntrospectionDialect; singlePk?: boolean },
): boolean {
  if ((col.is_identity ?? "").toUpperCase() === "YES") return true;

  const dataTypeLower = col.data_type.toLowerCase();
  if (dataTypeLower === "serial" || dataTypeLower === "bigserial") return true;

  const defaultVal = (col.column_default ?? "").toLowerCase();
  if (defaultVal.includes("nextval") || defaultVal.includes("auto_increment")) {
    return true;
  }

  const extra = (col.extra ?? "").toLowerCase();
  if (extra.includes("auto_increment")) return true;

  return (
    context?.dialect === "sqlite" &&
    context.singlePk === true &&
    dataTypeLower === "integer"
  );
}

/**
 * Detect whether a column should carry `@CreateTimestamp`, `@UpdateTimestamp`,
 * or `@DeletedAt` (`.createTimestamp()` / `.updateTimestamp()` / `.deletedAt()`
 * in the code-first style).
 */
function detectTimestampRole(
  propertyName: string,
  col: DbColumn,
  columnType: ColumnType,
): ModelColumnField["timestamp"] {
  const isTimestampType =
    columnType === "datetime" ||
    columnType === "timestamp" ||
    columnType === "timestamptz" ||
    columnType === "date";
  if (!isTimestampType) return undefined;

  const nullable = col.is_nullable === "YES";
  if (propertyName === "createdAt" && !nullable) return "create";
  if (propertyName === "updatedAt" && !nullable) return "update";
  if (propertyName === "deletedAt" && nullable) return "deletedAt";
  return undefined;
}

/**
 * Convert a raw `column_default` string from INFORMATION_SCHEMA into a
 * TypeScript literal. Returns `null` to omit the default entirely (no default,
 * or one the ORM owns itself such as a PK sequence / auto_increment).
 */
export function formatDefault(
  rawDefault: string | null | undefined,
  columnType: ColumnType,
): string | null {
  if (rawDefault === undefined || rawDefault === null) return null;
  const raw = rawDefault.trim();
  if (raw === "") return null;

  const lower = raw.toLowerCase();

  // Auto-generated PK defaults are owned by @PrimaryGeneratedColumn — skip.
  if (lower.startsWith("nextval(") || lower.includes("auto_increment")) {
    return null;
  }

  // MariaDB 10.2+ returns the literal string `NULL` from INFORMATION_SCHEMA
  // when a nullable column has no explicit default. Treat that — and any
  // other bare-NULL expression — as "no default".
  if (lower === "null") return null;

  // Strip PostgreSQL `::type` casts (e.g., `'foo'::character varying`).
  let stripped = raw;
  const castIdx = stripped.indexOf("::");
  if (castIdx !== -1) stripped = stripped.slice(0, castIdx).trim();

  // Boolean literals (Postgres: true/false; MySQL: 0/1 for tinyint(1)).
  if (columnType === "boolean") {
    const v = stripped.toLowerCase();
    if (v === "true" || v === "'t'" || v === "t" || v === "1") return "true";
    if (v === "false" || v === "'f'" || v === "f" || v === "0") return "false";
  }

  // Quoted string literal: `'value'` → keep as JS string.
  if (stripped.startsWith("'") && stripped.endsWith("'") && stripped.length >= 2) {
    const inner = stripped.slice(1, -1).replace(/''/g, "'");
    return JSON.stringify(inner);
  }

  // Numeric literal — only safe for numeric column types so we don't
  // accidentally re-classify a SQL function call.
  if (
    (columnType === "int" ||
      columnType === "bigint" ||
      columnType === "float" ||
      columnType === "double" ||
      columnType === "number") &&
    /^-?\d+(\.\d+)?$/.test(stripped)
  ) {
    return stripped;
  }

  // Anything else (CURRENT_TIMESTAMP, now(), uuid_generate_v4(), …) is a raw
  // SQL expression — wrapped in parentheses so the driver passes it through
  // as a function default rather than a quoted literal.
  return JSON.stringify(`(${stripped})`);
}

/**
 * Build the dialect-neutral {@link EntityModel} for one table.
 */
export interface EntityModelContext {
  /**
   * Primary key columns per table, when the caller has introspected the whole
   * schema. Used to flag a foreign key that points at a non-primary-key column
   * — schema generation always builds the constraint against the target's
   * primary key, so such a relation cannot be recreated faithfully.
   */
  primaryKeysByTable?: Record<string, string[]>;
}

export function buildEntityModel(
  tableName: string,
  columns: DbColumn[],
  pks: string[],
  fks: DbForeignKey[],
  dialect: IntrospectionDialect,
  indexes: DbIndex[] = [],
  context: EntityModelContext = {},
): EntityModel {
  const className = tableNameToClassName(tableName);
  const fkColumnSet = new Set(fks.map((fk) => fk.column_name));
  const columnByName = new Map(columns.map((c) => [c.column_name, c]));

  // Classify indexes: single-column non-unique → property-level index;
  // everything else (multi-column, or any unique) → class-level. Indexes that
  // exactly cover the primary key are dropped.
  const pkColumnSet = new Set(pks);
  const propertyLevelIndexCols = new Set<string>();
  const classLevelIndexes: DbIndex[] = [];
  for (const idx of indexes) {
    if (
      idx.column_names.length === pks.length &&
      idx.column_names.every((c) => pkColumnSet.has(c))
    ) {
      continue;
    }
    if (idx.column_names.length === 1 && !idx.is_unique) {
      propertyLevelIndexCols.add(idx.column_names[0]);
    } else {
      classLevelIndexes.push(idx);
    }
  }

  // Columns that are BOTH a FK and a PK (closure tables, join tables with
  // composite PKs) need a primary-key declaration in addition to the relation
  // — otherwise the entity has no primary key at all.
  const fkPkColumnSet = new Set(
    fks.filter((fk) => pks.includes(fk.column_name)).map((fk) => fk.column_name),
  );

  const fields: EntityModelField[] = [];
  const usedPropertyNames = new Set<string>();
  const colToProperty = new Map<string, string>();

  for (const col of columns) {
    colToProperty.set(col.column_name, columnNameToPropertyName(col.column_name));

    // Pure FK columns are represented as relations only. Composite-PK FK
    // columns are kept (see fkPkColumnSet).
    if (fkColumnSet.has(col.column_name) && !fkPkColumnSet.has(col.column_name)) {
      continue;
    }

    const propertyName = columnNameToPropertyName(col.column_name);
    usedPropertyNames.add(propertyName);

    const field = describeColumn(col, {
      propertyName,
      dialect,
      primary: pks.includes(col.column_name),
      fkPrimary: fkPkColumnSet.has(col.column_name),
      singlePk: pks.length === 1,
      index: propertyLevelIndexCols.has(col.column_name),
    });
    fields.push(field);
  }

  const referencedClasses = new Set<string>();

  for (const fk of fks) {
    const refClassName = tableNameToClassName(fk.referenced_table);
    if (refClassName !== className) referencedClasses.add(refClassName);

    // Default: strip the `_id` suffix (`author_id` → `author`). On a collision
    // with an existing column or another relation, fall back to the camelCased
    // FK column name, then to a numeric suffix.
    const base = fkToPropertyName(fk.column_name);
    const fallback = columnNameToPropertyName(fk.column_name);
    let propertyName = base;
    if (usedPropertyNames.has(propertyName) && fallback !== propertyName) {
      propertyName = fallback;
    }
    let suffix = 2;
    while (usedPropertyNames.has(propertyName)) {
      propertyName = `${base}${suffix++}`;
    }
    usedPropertyNames.add(propertyName);
    colToProperty.set(fk.column_name, propertyName);

    const fkCol = columnByName.get(fk.column_name);
    // The FK column's own type and nullability have to be pinned explicitly:
    // without them the ORM infers the type from the target's PK and defaults
    // the column to NULL-able, quietly dropping a NOT NULL from the source
    // schema.
    const fkType = fkCol
      ? resolveColumnType(fkCol, dialect)
      : ("int" as ColumnType);
    const fkNullable = fkCol ? fkCol.is_nullable === "YES" : true;

    const relation: ModelRelationField = {
      kind: "manyToOne",
      propertyName,
      targetClass: refClassName,
      selfReference: refClassName === className,
      fkColumn: fk.column_name,
      fkType,
      fkNullable,
      referencedColumn: fk.referenced_column,
    };

    const targetPks = context.primaryKeysByTable?.[fk.referenced_table];
    if (
      targetPks &&
      fk.referenced_column &&
      !(targetPks.length === 1 && targetPks[0] === fk.referenced_column)
    ) {
      relation.warnings = [
        `Foreign key "${fk.column_name}" references ` +
          `"${fk.referenced_table}"."${fk.referenced_column}", which is not ` +
          `that table's primary key (${targetPks.join(", ") || "none"}). ` +
          "Schema generation always builds the constraint against the " +
          "primary key, so synchronizing this entity would create a " +
          "different foreign key than the one in the database.",
      ];
    }

    fields.push(relation);
  }

  const classIndexes: ModelIndex[] = classLevelIndexes.map((idx) => ({
    columns: idx.column_names.map((c) => colToProperty.get(c) ?? c),
    // SQLite's implicit UNIQUE-constraint indexes carry reserved names
    // (sqlite_autoindex_<table>_<n>). Re-creating one by that name fails with
    // "object name reserved for internal use", so those are emitted unnamed
    // and schema sync picks its own name.
    name:
      idx.name && !/^sqlite_autoindex_/i.test(idx.name) ? idx.name : undefined,
    unique: idx.is_unique,
  }));

  return {
    tableName,
    className,
    fields,
    classIndexes,
    referencedClasses: Array.from(referencedClasses).sort(),
  };
}

/**
 * Resolve the ORM {@link ColumnType} for a raw introspected column, applying
 * the "unbounded varchar is really text" correction.
 *
 * A `character varying` with no length limit (PostgreSQL) or a bare `VARCHAR`
 * (SQLite) has no width to carry over, and the ORM's default column option
 * would silently cap the regenerated column at `VARCHAR(255)`.
 */
function resolveColumnType(
  col: DbColumn,
  dialect: IntrospectionDialect,
): ColumnType {
  const columnType = IntrospectionTypeMapper.toColumnType(
    col.data_type,
    dialect,
    col.column_type ?? undefined,
  );
  if (
    columnType === "varchar" &&
    (col.character_maximum_length === undefined ||
      col.character_maximum_length === null)
  ) {
    return "text";
  }
  return columnType;
}

function describeColumn(
  col: DbColumn,
  ctx: {
    propertyName: string;
    dialect: IntrospectionDialect;
    primary: boolean;
    fkPrimary: boolean;
    singlePk: boolean;
    index: boolean;
  },
): ModelColumnField {
  const columnType = resolveColumnType(col, ctx.dialect);
  // A primary key is never nullable, whatever the catalog says — SQLite
  // reports `notnull = 0` for an `INTEGER PRIMARY KEY` rowid alias.
  const nullable = ctx.primary ? false : col.is_nullable === "YES";
  const timestamp = detectTimestampRole(ctx.propertyName, col, columnType);
  const generated =
    ctx.primary &&
    isGeneratedPrimaryKey(col, {
      dialect: ctx.dialect,
      singlePk: ctx.singlePk,
    });

  const baseTsType = timestamp
    ? "Date"
    : IntrospectionTypeMapper.toTsType(columnType);
  // A nullable column really can hold null — say so, rather than handing the
  // caller a property type the database can violate.
  const tsType =
    nullable && baseTsType !== "any" ? `${baseTsType} | null` : baseTsType;

  const field: ModelColumnField = {
    kind: "column",
    propertyName: ctx.propertyName,
    columnName: col.column_name,
    needsNameOption: col.column_name !== ctx.propertyName,
    columnType,
    tsType,
    nullable,
    primary: ctx.primary,
    generated,
    fkPrimary: ctx.fkPrimary,
    index: ctx.index,
    timestamp,
  };

  if (
    (columnType === "varchar" || columnType === "char") &&
    col.character_maximum_length !== undefined &&
    col.character_maximum_length !== null
  ) {
    field.length = col.character_maximum_length;
  }

  if (
    (columnType === "float" ||
      columnType === "double" ||
      columnType === "number") &&
    DECIMAL_SOURCE_TYPES.has(col.data_type.toLowerCase()) &&
    col.numeric_precision !== undefined &&
    col.numeric_precision !== null
  ) {
    field.precision = col.numeric_precision;
    if (col.numeric_scale !== undefined && col.numeric_scale !== null) {
      field.scale = col.numeric_scale;
    }
  }

  if (
    columnType === "enum" &&
    Array.isArray(col.enum_values) &&
    col.enum_values.length > 0
  ) {
    field.enumValues = col.enum_values;
  }

  const defaultLiteral = formatDefault(col.column_default, columnType);
  if (defaultLiteral !== null) field.defaultLiteral = defaultLiteral;

  const warnings = describeMappingWarnings(col, columnType, ctx.dialect);
  if (warnings.length > 0) field.warnings = warnings;

  return field;
}

/**
 * Notes about a mapping that cannot survive a round trip, so the generated
 * file says so out loud.
 */
function describeMappingWarnings(
  col: DbColumn,
  columnType: ColumnType,
  dialect: IntrospectionDialect,
): string[] {
  const warnings: string[] = [];
  const rawType = (col.column_type ?? col.data_type ?? "").trim();

  if (!IntrospectionTypeMapper.hasMapping(col.data_type, dialect)) {
    warnings.push(
      `Unrecognized database type "${rawType}" — mapped to "${columnType}". ` +
        "Synchronizing this entity will NOT recreate the original type; " +
        "register a custom column type or edit this column by hand.",
    );
  } else if (
    dialect === "postgres" &&
    ["double precision", "float8", "real", "float4"].includes(
      col.data_type.toLowerCase(),
    )
  ) {
    warnings.push(
      `"${col.data_type}" has no exact ORM column type — mapped to ` +
        `"${columnType}", which this ORM emits as ` +
        (columnType === "double" ? "NUMERIC" : "REAL") +
        " on PostgreSQL.",
    );
  }

  return warnings;
}
