import type { ColumnType } from "../decorators/Column";
import type { ReferentialAction } from "../types/ReferentialAction";
import { dialectTypes } from "./catalog";
import {
  DbColumn,
  DbForeignKey,
  DbIndex,
  tableFromLegacyRows,
} from "./catalog/legacyRows";
import { lowerTable } from "./lowering/lowerTable";
import { SchemaNaming } from "./lowering/Naming";
import { TypeOracle } from "./lowering/TypeSelection";
import type { IntrospectionDialect } from "./TypeMapper";

/**
 * One entity as the ORM will declare it — the lowered form of a table.
 *
 * Built from the dialect-neutral {@link TableIR} by `lowering/lowerTable.ts`
 * and consumed by both code emitters, so the decorator and the code-first
 * output can never disagree about what a table means; they only differ in
 * how they spell it.
 */
export interface EntityModel {
  tableName: string;
  className: string;
  /** Stored columns and relations, in the order they should be emitted. */
  fields: EntityModelField[];
  /**
   * Class-level indexes. A plain column is named by its *property*; a column
   * that only exists as a relation's join column is named by its DB column,
   * which the index declarations resolve to itself.
   */
  classIndexes: ModelIndex[];
  /** Class names referenced by relations (FK targets), excluding self. */
  referencedClasses: string[];
  /**
   * What the entity cannot say about the table as a whole — a composite
   * foreign key, an index the ORM cannot declare, a missing primary key.
   * Emitted as `// NOTE:` comments above the entity.
   */
  notes: string[];
}

export type EntityModelField = ModelColumnField | ModelRelationField;

/** A stored column. */
export interface ModelColumnField {
  kind: "column";
  propertyName: string;
  columnName: string;
  /** True when the DB column name differs from the property name. */
  needsNameOption: boolean;
  columnType: ColumnType;
  /** TypeScript type of the property, already widened for nullability. */
  tsType: string;
  nullable: boolean;
  primary: boolean;
  /** Primary key generated by the database (serial / auto_increment / rowid). */
  generated: boolean;
  /** A column that is both a FK and part of the PK — emitted as a plain PK column. */
  fkPrimary: boolean;
  length?: number;
  precision?: number;
  scale?: number;
  enumValues?: string[];
  /** PostgreSQL enum type name. */
  enumName?: string;
  /** Element type of a PostgreSQL array column. */
  arrayElementType?: ColumnType;
  /** Default value as a TypeScript literal source string (already quoted). */
  defaultLiteral?: string;
  /** Single-column, non-unique index on this column. */
  index: boolean;
  /** Timestamp role detected from the property name, type, and nullability. */
  timestamp?: "create" | "update" | "deletedAt";
  /**
   * Lossy-mapping notes emitted as comments above the field, so a mapping the
   * generator could not make faithful is visible in the generated file instead
   * of only showing up the next time the schema is synchronized.
   */
  warnings?: string[];
}

/** A `@ManyToOne` relation standing in for a foreign key column. */
export interface ModelRelationField {
  kind: "manyToOne";
  propertyName: string;
  targetClass: string;
  /** True when the FK points back at the same table. */
  selfReference: boolean;
  fkColumn: string;
  fkType: ColumnType;
  fkNullable: boolean;
  referencedColumn?: string;
  /** Declared when the constraint has an action other than NO ACTION. */
  onDelete?: ReferentialAction;
  onUpdate?: ReferentialAction;
  /** Lossy-mapping notes, emitted as comments above the relation. */
  warnings?: string[];
}

export interface ModelIndex {
  /** Property names, or DB column names for relation join columns. */
  columns: string[];
  name?: string;
  unique: boolean;
}

/** Whole-schema facts for {@link buildEntityModel}. */
export interface EntityModelContext {
  /**
   * Primary key columns per table, when the caller has introspected the whole
   * schema. Used to flag a foreign key that points at a non-primary-key column
   * — schema generation always builds the constraint against the target's
   * primary key, so such a relation cannot be recreated faithfully.
   */
  primaryKeysByTable?: Record<string, string[]>;
}

/**
 * Builds the {@link EntityModel} for one table from the original row shapes.
 *
 * The rows are read into the IR first, exactly as a catalog reader would
 * produce it, so this goes through the same lowering as the generator.
 * Referenced tables are assumed to be generated alongside this one.
 */
export function buildEntityModel(
  tableName: string,
  columns: DbColumn[],
  pks: string[],
  fks: DbForeignKey[],
  dialect: IntrospectionDialect,
  indexes: DbIndex[] = [],
  context: EntityModelContext = {},
): EntityModel {
  const table = tableFromLegacyRows(dialect, tableName, columns, pks, fks, indexes);
  const types = dialectTypes(dialect);
  return lowerTable(table, {
    types,
    oracle: new TypeOracle(types),
    naming: new SchemaNaming([tableName]),
    primaryKeysByTable: context.primaryKeysByTable,
  });
}
