/**
 * ORM 에러 코드 열거형입니다.
 * 각 에러 유형에 고유한 코드를 부여하여 프로그래밍 방식으로 에러를 식별할 수 있습니다.
 */
export enum OrmErrorCode {
  // 연결 관련
  CONNECTION_FAILED = "ORM_CONNECTION_FAILED",
  NOT_CONNECTED = "ORM_NOT_CONNECTED",
  UNSUPPORTED_DATABASE = "ORM_UNSUPPORTED_DATABASE",

  // 엔티티 관련
  ENTITY_NOT_FOUND = "ORM_ENTITY_NOT_FOUND",
  ENTITY_METADATA_NOT_FOUND = "ORM_ENTITY_METADATA_NOT_FOUND",
  PRIMARY_KEY_NOT_FOUND = "ORM_PRIMARY_KEY_NOT_FOUND",

  // 쿼리 관련
  INVALID_QUERY = "ORM_INVALID_QUERY",
  DELETE_WITHOUT_CONDITIONS = "ORM_DELETE_WITHOUT_CONDITIONS",
  QUERY_TIMEOUT = "ORM_QUERY_TIMEOUT",

  // 트랜잭션 관련
  TRANSACTION_FAILED = "ORM_TRANSACTION_FAILED",
  TRANSACTION_ROLLBACK_FAILED = "ORM_TRANSACTION_ROLLBACK_FAILED",

  // 유효성 검사
  VALIDATION_FAILED = "ORM_VALIDATION_FAILED",
}
