/**
 * ORM error code enumeration.
 * Each error type has a unique code so errors can be identified programmatically.
 */
export enum OrmErrorCode {
  // Connection
  CONNECTION_FAILED = "ORM_CONNECTION_FAILED",
  NOT_CONNECTED = "ORM_NOT_CONNECTED",
  UNSUPPORTED_DATABASE = "ORM_UNSUPPORTED_DATABASE",

  // Entity
  ENTITY_NOT_FOUND = "ORM_ENTITY_NOT_FOUND",
  ENTITY_METADATA_NOT_FOUND = "ORM_ENTITY_METADATA_NOT_FOUND",
  PRIMARY_KEY_NOT_FOUND = "ORM_PRIMARY_KEY_NOT_FOUND",

  // Query
  INVALID_QUERY = "ORM_INVALID_QUERY",
  DELETE_WITHOUT_CONDITIONS = "ORM_DELETE_WITHOUT_CONDITIONS",
  QUERY_TIMEOUT = "ORM_QUERY_TIMEOUT",

  // Transaction
  TRANSACTION_FAILED = "ORM_TRANSACTION_FAILED",
  TRANSACTION_ROLLBACK_FAILED = "ORM_TRANSACTION_ROLLBACK_FAILED",

  // Locking
  ADVISORY_LOCK_FAILED = "ORM_ADVISORY_LOCK_FAILED",
  OPTIMISTIC_LOCK_FAILED = "ORM_OPTIMISTIC_LOCK_FAILED",

  // Validation
  VALIDATION_FAILED = "ORM_VALIDATION_FAILED",

  // Savepoint
  INVALID_SAVEPOINT_NAME = "ORM_INVALID_SAVEPOINT_NAME",

  // Constraint violations
  UNIQUE_VIOLATION = "ORM_UNIQUE_VIOLATION",
  FK_VIOLATION = "ORM_FK_VIOLATION",

  // Unsupported operation
  UNSUPPORTED_OPERATION = "ORM_UNSUPPORTED_OPERATION",

  // Entity glob
  ENTITY_GLOB_NO_MATCH = "ORM_ENTITY_GLOB_NO_MATCH",

  // Prisma import
  PRISMA_PARSE_ERROR = "ORM_PRISMA_PARSE_ERROR",
  MISSING_DEPENDENCY = "ORM_MISSING_DEPENDENCY",

  // Plugin system
  PLUGIN_DEPENDENCY_MISSING = "ORM_PLUGIN_DEPENDENCY_MISSING",
  PLUGIN_CONFLICT = "ORM_PLUGIN_CONFLICT",
  BUFFER_NOT_INSTALLED = "ORM_BUFFER_NOT_INSTALLED",

  // Query Builder
  MISSING_REQUIRED_COLUMNS = "ORM_MISSING_REQUIRED_COLUMNS",
  MISSING_PLACEHOLDER = "ORM_MISSING_PLACEHOLDER",

  // Schema
  SCHEMA_ERROR = "ORM_SCHEMA_ERROR",
  SCHEMA_SYNC_FAILED = "ORM_SCHEMA_SYNC_FAILED",
  SCHEMA_SYNC_DESTRUCTIVE_CHANGE = "ORM_SCHEMA_SYNC_DESTRUCTIVE_CHANGE",

  // Validation
  VALIDATION_ERROR = "ORM_VALIDATION_ERROR",

  // Query
  QUERY_ERROR = "ORM_QUERY_ERROR",

  // Configuration
  INVALID_CONFIG = "ORM_INVALID_CONFIG",

  // Multi-tenancy
  MISSING_TENANT_CONTEXT = "ORM_MISSING_TENANT_CONTEXT",
  TENANT_MISMATCH = "ORM_TENANT_MISMATCH",
  CROSS_TENANT_TRANSACTION = "ORM_CROSS_TENANT_TRANSACTION",
  TENANT_RESOLVER_MISSING = "ORM_TENANT_RESOLVER_MISSING",
}
