/**
 * Auto-generated by scripts/generate-baseline.ts on 2026-05-07T13:39:46.385Z.
 *
 * Frozen baseline: the DDL arrays below are the literal schema as of
 * generation. Re-running the script overwrites this file. Once it is
 * checked in, edit the generator instead of the file by hand.
 *
 * Apply with: pnpm migrate:run
 * Roll back with: pnpm migrate:rollback
 */
import { Migration, MigrationContext } from "@stingerloom/orm";

const MYSQL_UP: string[] = [
      `CREATE TABLE IF NOT EXISTS \`workspace\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`name\` VARCHAR(255) NOT NULL, \`slug\` VARCHAR(255) NOT NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`user\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`email\` VARCHAR(255) NOT NULL, \`name\` VARCHAR(255) NOT NULL, \`avatar_url\` VARCHAR(255) NULL, \`password_hash\` VARCHAR(100) NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`membership\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`role\` VARCHAR(16) NOT NULL, \`joined_at\` DATETIME NULL, \`workspace_id\` INT NULL, \`user_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`project\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`name\` VARCHAR(255) NOT NULL, \`key\` VARCHAR(16) NOT NULL, \`description\` TEXT NULL, \`custom_field_schema\` JSON NULL, \`issue_counter\` INT(11) NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL, \`workspace_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`sprint\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`name\` VARCHAR(255) NOT NULL, \`status\` VARCHAR(16) NOT NULL, \`start_date\` DATETIME NULL, \`end_date\` DATETIME NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL, \`project_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`issue\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`number\` INT(11) NOT NULL, \`title\` VARCHAR(255) NOT NULL, \`description\` TEXT NULL, \`status\` VARCHAR(16) NOT NULL, \`priority\` INT(11) NULL, \`estimate\` INT(11) NULL, \`custom_fields\` JSON NULL, \`claimed_by\` VARCHAR(64) NULL, \`claimed_at\` DATETIME NULL, \`version\` INT(11) NOT NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL, \`completed_at\` DATETIME NULL, \`deleted_at\` DATETIME NULL, \`project_id\` INT NULL, \`sprint_id\` INT NULL, \`assignee_id\` INT NULL, \`reporter_id\` INT NULL, \`parent_id\` INT NULL, \`cycleTimeHours\` INT GENERATED ALWAYS AS ((CASE WHEN deleted_at IS NULL AND completed_at IS NOT NULL THEN TIMESTAMPDIFF(HOUR, created_at, completed_at) ELSE NULL END)) VIRTUAL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`label\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`name\` VARCHAR(255) NOT NULL, \`color\` VARCHAR(16) NULL, \`created_at\` DATETIME NULL, \`project_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`comment\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`body\` TEXT NOT NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL, \`deleted_at\` DATETIME NULL, \`issue_id\` INT NULL, \`author_id\` INT NULL, \`parent_comment_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`comment_revision\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`body\` TEXT NOT NULL, \`edited_at\` DATETIME NOT NULL, \`comment_id\` INT NULL, \`editor_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`reaction\` (\`comment_id\` INT(11) NOT NULL, \`user_id\` INT(11) NOT NULL, \`emoji\` VARCHAR(32) NOT NULL, \`created_at\` DATETIME NOT NULL, PRIMARY KEY (\`comment_id\`, \`user_id\`, \`emoji\`)) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`activity_log\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`workspace_id\` INT(11) NULL, \`issue_id\` INT(11) NOT NULL, \`actor_user_id\` INT(11) NULL, \`action\` VARCHAR(32) NOT NULL, \`payload\` JSON NULL, \`created_at\` DATETIME NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`issue_link\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`type\` VARCHAR(16) NOT NULL, \`created_by\` INT(11) NULL, \`created_at\` DATETIME NOT NULL, \`source_issue_id\` INT NULL, \`target_issue_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`saved_filter\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`name\` VARCHAR(128) NOT NULL, \`definition\` JSON NULL, \`created_at\` DATETIME NULL, \`updated_at\` DATETIME NULL, \`workspace_id\` INT NULL, \`owner_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`workflow_definition\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`states\` JSON NULL, \`created_at\` DATETIME NOT NULL, \`project_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`workflow_transition\` (\`definition_id\` INT(11) NOT NULL, \`from_state\` VARCHAR(32) NOT NULL, \`to_state\` VARCHAR(32) NOT NULL, \`required_role\` VARCHAR(16) NULL, \`required_fields\` JSON NULL, \`created_at\` DATETIME NOT NULL, PRIMARY KEY (\`definition_id\`, \`from_state\`, \`to_state\`)) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`issue_watcher\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`last_seen_at\` DATETIME NULL, \`created_at\` DATETIME NOT NULL, \`issue_id\` INT NULL, \`user_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`notification\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`kind\` VARCHAR(32) NOT NULL, \`payload\` JSON NULL, \`read_at\` DATETIME NULL, \`created_at\` DATETIME NOT NULL, \`user_id\` INT NULL, \`source_issue_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`webhook_endpoint\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`url\` VARCHAR(512) NOT NULL, \`secret\` VARCHAR(64) NOT NULL, \`events\` JSON NULL, \`is_active\` TINYINT(1) NOT NULL DEFAULT 1, \`created_at\` DATETIME NULL, \`workspace_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`webhook_delivery\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`event_type\` VARCHAR(64) NOT NULL, \`payload\` JSON NULL, \`state\` VARCHAR(16) NOT NULL, \`attempt_count\` INT(11) NOT NULL DEFAULT 0, \`next_attempt_at\` DATETIME NULL, \`last_attempted_at\` DATETIME NULL, \`last_error\` TEXT NULL, \`idempotency_key\` VARCHAR(64) NOT NULL, \`created_at\` DATETIME NULL, \`endpoint_id\` INT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`bulk_operation\` (\`id\` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, \`idempotency_key\` VARCHAR(128) NOT NULL, \`actor_user_id\` INT(11) NULL, \`status\` VARCHAR(16) NOT NULL, \`request_hash\` VARCHAR(64) NOT NULL, \`total_count\` INT(11) NOT NULL, \`success_count\` INT(11) NOT NULL DEFAULT 0, \`conflict_count\` INT(11) NOT NULL DEFAULT 0, \`not_found_count\` INT(11) NOT NULL DEFAULT 0, \`results\` JSON NULL, \`created_at\` DATETIME NOT NULL, \`completed_at\` DATETIME NOT NULL) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS \`idempotency_key\` (\`key\` VARCHAR(128) NOT NULL PRIMARY KEY, \`user_id\` INT(11) NULL, \`request_hash\` VARCHAR(64) NOT NULL, \`status\` VARCHAR(16) NOT NULL, \`http_status\` INT(11) NULL, \`response\` JSON NULL, \`created_at\` DATETIME NULL, \`expires_at\` DATETIME NOT NULL) ENGINE=InnoDB`,
      `CREATE INDEX \`idx_membership_user_id\` ON \`membership\` (\`user_id\`)`,
      `CREATE INDEX \`idx_sprint_project_id_status\` ON \`sprint\` (\`project_id\`, \`status\`)`,
      `CREATE INDEX \`idx_issue_sprint_id\` ON \`issue\` (\`sprint_id\`)`,
      `CREATE INDEX \`idx_issue_parent_id\` ON \`issue\` (\`parent_id\`)`,
      `CREATE INDEX \`idx_issue_assignee_id\` ON \`issue\` (\`assignee_id\`)`,
      `CREATE INDEX \`idx_issue_project_id_status\` ON \`issue\` (\`project_id\`, \`status\`)`,
      `CREATE INDEX \`idx_comment_issue_id_parent_comment_id\` ON \`comment\` (\`issue_id\`, \`parent_comment_id\`)`,
      `CREATE INDEX \`idx_comment_author_id\` ON \`comment\` (\`author_id\`)`,
      `CREATE INDEX \`idx_comment_issue_id_created_at\` ON \`comment\` (\`issue_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_comment_revision_comment_id_edited_at\` ON \`comment_revision\` (\`comment_id\`, \`edited_at\`)`,
      `CREATE INDEX \`idx_reaction_comment_id\` ON \`reaction\` (\`comment_id\`)`,
      `CREATE INDEX \`idx_activity_log_action\` ON \`activity_log\` (\`action\`)`,
      `CREATE INDEX \`idx_activity_log_actor_user_id_created_at\` ON \`activity_log\` (\`actor_user_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_activity_log_workspace_id_created_at\` ON \`activity_log\` (\`workspace_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_activity_log_issue_id_created_at\` ON \`activity_log\` (\`issue_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_issue_link_target_issue_id_type\` ON \`issue_link\` (\`target_issue_id\`, \`type\`)`,
      `CREATE INDEX \`idx_saved_filter_workspace_id_owner_id\` ON \`saved_filter\` (\`workspace_id\`, \`owner_id\`)`,
      `CREATE INDEX \`idx_workflow_transition_definition_id_from_state\` ON \`workflow_transition\` (\`definition_id\`, \`from_state\`)`,
      `CREATE INDEX \`idx_issue_watcher_user_id_last_seen_at\` ON \`issue_watcher\` (\`user_id\`, \`last_seen_at\`)`,
      `CREATE INDEX \`idx_notification_source_issue_id_created_at\` ON \`notification\` (\`source_issue_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_notification_user_id_read_at\` ON \`notification\` (\`user_id\`, \`read_at\`)`,
      `CREATE INDEX \`idx_webhook_endpoint_workspace_id\` ON \`webhook_endpoint\` (\`workspace_id\`)`,
      `CREATE INDEX \`idx_webhook_delivery_endpoint_id_created_at\` ON \`webhook_delivery\` (\`endpoint_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_webhook_delivery_state_next_attempt_at\` ON \`webhook_delivery\` (\`state\`, \`next_attempt_at\`)`,
      `CREATE INDEX \`idx_bulk_operation_actor_user_id_created_at\` ON \`bulk_operation\` (\`actor_user_id\`, \`created_at\`)`,
      `CREATE INDEX \`idx_idempotency_key_expires_at\` ON \`idempotency_key\` (\`expires_at\`)`,
      `CREATE FULLTEXT INDEX \`fts_issue_title_description\` ON \`issue\` (\`title\`, \`description\`)`,
      `CREATE FULLTEXT INDEX \`fts_comment_body\` ON \`comment\` (\`body\`)`,
      `CREATE UNIQUE INDEX \`uq_workspace_slug\` ON \`workspace\` (\`slug\`)`,
      `CREATE UNIQUE INDEX \`uq_user_email\` ON \`user\` (\`email\`)`,
      `CREATE UNIQUE INDEX \`uq_membership_workspace_id_user_id\` ON \`membership\` (\`workspace_id\`, \`user_id\`)`,
      `CREATE UNIQUE INDEX \`uq_project_workspace_id_key\` ON \`project\` (\`workspace_id\`, \`key\`)`,
      `CREATE UNIQUE INDEX \`uq_issue_project_id_number\` ON \`issue\` (\`project_id\`, \`number\`)`,
      `CREATE UNIQUE INDEX \`uq_label_project_id_name\` ON \`label\` (\`project_id\`, \`name\`)`,
      `CREATE UNIQUE INDEX \`uq_issue_link_source_issue_id_target_issue_id_type\` ON \`issue_link\` (\`source_issue_id\`, \`target_issue_id\`, \`type\`)`,
      `CREATE UNIQUE INDEX \`uq_workflow_definition_project_id\` ON \`workflow_definition\` (\`project_id\`)`,
      `CREATE UNIQUE INDEX \`uq_issue_watcher_issue_id_user_id\` ON \`issue_watcher\` (\`issue_id\`, \`user_id\`)`,
      `CREATE UNIQUE INDEX \`uq_webhook_endpoint_workspace_id_url\` ON \`webhook_endpoint\` (\`workspace_id\`, \`url\`)`,
      `CREATE UNIQUE INDEX \`uq_webhook_delivery_idempotency_key\` ON \`webhook_delivery\` (\`idempotency_key\`)`,
      `CREATE UNIQUE INDEX \`uq_bulk_operation_idempotency_key\` ON \`bulk_operation\` (\`idempotency_key\`)`,
      `CREATE TABLE IF NOT EXISTS \`issue_labels\` (\`issue_id\` INT NOT NULL, \`label_id\` INT NOT NULL, PRIMARY KEY (\`issue_id\`, \`label_id\`)) ENGINE=InnoDB`,
      `ALTER TABLE \`issue_labels\` ADD CONSTRAINT fk_issue_labels_44f3203f FOREIGN KEY (\`issue_id\`) REFERENCES \`issue\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
      `ALTER TABLE \`issue_labels\` ADD CONSTRAINT fk_issue_labels_d5d688ce FOREIGN KEY (\`label_id\`) REFERENCES \`label\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`
];

const MYSQL_DOWN: string[] = [
      `DROP TABLE IF EXISTS \`issue_labels\``,
      `DROP TABLE IF EXISTS \`idempotency_key\``,
      `DROP TABLE IF EXISTS \`bulk_operation\``,
      `DROP TABLE IF EXISTS \`webhook_delivery\``,
      `DROP TABLE IF EXISTS \`webhook_endpoint\``,
      `DROP TABLE IF EXISTS \`notification\``,
      `DROP TABLE IF EXISTS \`issue_watcher\``,
      `DROP TABLE IF EXISTS \`workflow_transition\``,
      `DROP TABLE IF EXISTS \`workflow_definition\``,
      `DROP TABLE IF EXISTS \`saved_filter\``,
      `DROP TABLE IF EXISTS \`issue_link\``,
      `DROP TABLE IF EXISTS \`activity_log\``,
      `DROP TABLE IF EXISTS \`reaction\``,
      `DROP TABLE IF EXISTS \`comment_revision\``,
      `DROP TABLE IF EXISTS \`comment\``,
      `DROP TABLE IF EXISTS \`label\``,
      `DROP TABLE IF EXISTS \`issue\``,
      `DROP TABLE IF EXISTS \`sprint\``,
      `DROP TABLE IF EXISTS \`project\``,
      `DROP TABLE IF EXISTS \`membership\``,
      `DROP TABLE IF EXISTS \`user\``,
      `DROP TABLE IF EXISTS \`workspace\``
];

const POSTGRES_UP: string[] = [
      `CREATE TABLE IF NOT EXISTS "public"."workspace" ("id" SERIAL NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "slug" VARCHAR(255) NOT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."user" ("id" SERIAL NOT NULL PRIMARY KEY, "email" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "avatar_url" VARCHAR(255) NULL, "password_hash" VARCHAR(100) NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."membership" ("id" SERIAL NOT NULL PRIMARY KEY, "role" VARCHAR(16) NOT NULL, "joined_at" TIMESTAMP NULL, "workspace_id" INTEGER NULL, "user_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."project" ("id" SERIAL NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "key" VARCHAR(16) NOT NULL, "description" TEXT NULL, "custom_field_schema" JSON NULL, "issue_counter" INTEGER NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL, "workspace_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."sprint" ("id" SERIAL NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "status" VARCHAR(16) NOT NULL, "start_date" TIMESTAMP NULL, "end_date" TIMESTAMP NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL, "project_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."issue" ("id" SERIAL NOT NULL PRIMARY KEY, "number" INTEGER NOT NULL, "title" VARCHAR(255) NOT NULL, "description" TEXT NULL, "status" VARCHAR(16) NOT NULL, "priority" INTEGER NULL, "estimate" INTEGER NULL, "custom_fields" JSON NULL, "claimed_by" VARCHAR(64) NULL, "claimed_at" TIMESTAMP NULL, "version" INTEGER NOT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL, "completed_at" TIMESTAMP NULL, "deleted_at" TIMESTAMP NULL, "project_id" INTEGER NULL, "sprint_id" INTEGER NULL, "assignee_id" INTEGER NULL, "reporter_id" INTEGER NULL, "parent_id" INTEGER NULL, "cycleTimeHours" INTEGER GENERATED ALWAYS AS ((CASE WHEN deleted_at IS NULL AND completed_at IS NOT NULL THEN EXTRACT(EPOCH FROM (completed_at - created_at)) / 3600 ELSE NULL END)) VIRTUAL)`,
      `CREATE TABLE IF NOT EXISTS "public"."label" ("id" SERIAL NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "color" VARCHAR(16) NULL, "created_at" TIMESTAMP NULL, "project_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."comment" ("id" SERIAL NOT NULL PRIMARY KEY, "body" TEXT NOT NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL, "deleted_at" TIMESTAMP NULL, "issue_id" INTEGER NULL, "author_id" INTEGER NULL, "parent_comment_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."comment_revision" ("id" SERIAL NOT NULL PRIMARY KEY, "body" TEXT NOT NULL, "edited_at" TIMESTAMP NOT NULL, "comment_id" INTEGER NULL, "editor_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."reaction" ("comment_id" INTEGER NOT NULL, "user_id" INTEGER NOT NULL, "emoji" VARCHAR(32) NOT NULL, "created_at" TIMESTAMP NOT NULL, PRIMARY KEY ("comment_id", "user_id", "emoji"))`,
      `CREATE TABLE IF NOT EXISTS "public"."activity_log" ("id" SERIAL NOT NULL PRIMARY KEY, "workspace_id" INTEGER NULL, "issue_id" INTEGER NOT NULL, "actor_user_id" INTEGER NULL, "action" VARCHAR(32) NOT NULL, "payload" JSON NULL, "created_at" TIMESTAMP NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."issue_link" ("id" SERIAL NOT NULL PRIMARY KEY, "type" VARCHAR(16) NOT NULL, "created_by" INTEGER NULL, "created_at" TIMESTAMP NOT NULL, "source_issue_id" INTEGER NULL, "target_issue_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."saved_filter" ("id" SERIAL NOT NULL PRIMARY KEY, "name" VARCHAR(128) NOT NULL, "definition" JSON NULL, "created_at" TIMESTAMP NULL, "updated_at" TIMESTAMP NULL, "workspace_id" INTEGER NULL, "owner_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."workflow_definition" ("id" SERIAL NOT NULL PRIMARY KEY, "states" JSON NULL, "created_at" TIMESTAMP NOT NULL, "project_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."workflow_transition" ("definition_id" INTEGER NOT NULL, "from_state" VARCHAR(32) NOT NULL, "to_state" VARCHAR(32) NOT NULL, "required_role" VARCHAR(16) NULL, "required_fields" JSON NULL, "created_at" TIMESTAMP NOT NULL, PRIMARY KEY ("definition_id", "from_state", "to_state"))`,
      `CREATE TABLE IF NOT EXISTS "public"."issue_watcher" ("id" SERIAL NOT NULL PRIMARY KEY, "last_seen_at" TIMESTAMP NULL, "created_at" TIMESTAMP NOT NULL, "issue_id" INTEGER NULL, "user_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."notification" ("id" SERIAL NOT NULL PRIMARY KEY, "kind" VARCHAR(32) NOT NULL, "payload" JSON NULL, "read_at" TIMESTAMP NULL, "created_at" TIMESTAMP NOT NULL, "user_id" INTEGER NULL, "source_issue_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."webhook_endpoint" ("id" SERIAL NOT NULL PRIMARY KEY, "url" VARCHAR(512) NOT NULL, "secret" VARCHAR(64) NOT NULL, "events" JSON NULL, "is_active" BOOLEAN NOT NULL DEFAULT TRUE, "created_at" TIMESTAMP NULL, "workspace_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."webhook_delivery" ("id" SERIAL NOT NULL PRIMARY KEY, "event_type" VARCHAR(64) NOT NULL, "payload" JSON NULL, "state" VARCHAR(16) NOT NULL, "attempt_count" INTEGER NOT NULL DEFAULT 0, "next_attempt_at" TIMESTAMP NULL, "last_attempted_at" TIMESTAMP NULL, "last_error" TEXT NULL, "idempotency_key" VARCHAR(64) NOT NULL, "created_at" TIMESTAMP NULL, "endpoint_id" INTEGER NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."bulk_operation" ("id" SERIAL NOT NULL PRIMARY KEY, "idempotency_key" VARCHAR(128) NOT NULL, "actor_user_id" INTEGER NULL, "status" VARCHAR(16) NOT NULL, "request_hash" VARCHAR(64) NOT NULL, "total_count" INTEGER NOT NULL, "success_count" INTEGER NOT NULL DEFAULT 0, "conflict_count" INTEGER NOT NULL DEFAULT 0, "not_found_count" INTEGER NOT NULL DEFAULT 0, "results" JSON NULL, "created_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS "public"."idempotency_key" ("key" VARCHAR(128) NOT NULL PRIMARY KEY, "user_id" INTEGER NULL, "request_hash" VARCHAR(64) NOT NULL, "status" VARCHAR(16) NOT NULL, "http_status" INTEGER NULL, "response" JSON NULL, "created_at" TIMESTAMP NULL, "expires_at" TIMESTAMP NOT NULL)`,
      `CREATE INDEX IF NOT EXISTS "idx_membership_user_id" ON "public"."membership" ("user_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_sprint_project_id_status" ON "public"."sprint" ("project_id", "status")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_sprint_id" ON "public"."issue" ("sprint_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_parent_id" ON "public"."issue" ("parent_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_assignee_id" ON "public"."issue" ("assignee_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_project_id_status" ON "public"."issue" ("project_id", "status")`,
      `CREATE INDEX IF NOT EXISTS "idx_comment_issue_id_parent_comment_id" ON "public"."comment" ("issue_id", "parent_comment_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_comment_author_id" ON "public"."comment" ("author_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_comment_issue_id_created_at" ON "public"."comment" ("issue_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_comment_revision_comment_id_edited_at" ON "public"."comment_revision" ("comment_id", "edited_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_reaction_comment_id" ON "public"."reaction" ("comment_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_activity_log_action" ON "public"."activity_log" ("action")`,
      `CREATE INDEX IF NOT EXISTS "idx_activity_log_actor_user_id_created_at" ON "public"."activity_log" ("actor_user_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_activity_log_workspace_id_created_at" ON "public"."activity_log" ("workspace_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_activity_log_issue_id_created_at" ON "public"."activity_log" ("issue_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_link_target_issue_id_type" ON "public"."issue_link" ("target_issue_id", "type")`,
      `CREATE INDEX IF NOT EXISTS "idx_saved_filter_workspace_id_owner_id" ON "public"."saved_filter" ("workspace_id", "owner_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_workflow_transition_definition_id_from_state" ON "public"."workflow_transition" ("definition_id", "from_state")`,
      `CREATE INDEX IF NOT EXISTS "idx_issue_watcher_user_id_last_seen_at" ON "public"."issue_watcher" ("user_id", "last_seen_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_notification_source_issue_id_created_at" ON "public"."notification" ("source_issue_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_notification_user_id_read_at" ON "public"."notification" ("user_id", "read_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_webhook_endpoint_workspace_id" ON "public"."webhook_endpoint" ("workspace_id")`,
      `CREATE INDEX IF NOT EXISTS "idx_webhook_delivery_endpoint_id_created_at" ON "public"."webhook_delivery" ("endpoint_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_webhook_delivery_state_next_attempt_at" ON "public"."webhook_delivery" ("state", "next_attempt_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_bulk_operation_actor_user_id_created_at" ON "public"."bulk_operation" ("actor_user_id", "created_at")`,
      `CREATE INDEX IF NOT EXISTS "idx_idempotency_key_expires_at" ON "public"."idempotency_key" ("expires_at")`,
      `CREATE INDEX IF NOT EXISTS "fts_issue_title_description" ON "public"."issue" USING gin (to_tsvector('english', "title" || ' ' || "description"))`,
      `CREATE INDEX IF NOT EXISTS "fts_comment_body" ON "public"."comment" USING gin (to_tsvector('english', "body"))`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_workspace_slug" ON "public"."workspace" ("slug")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_email" ON "public"."user" ("email")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_membership_workspace_id_user_id" ON "public"."membership" ("workspace_id", "user_id")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_project_workspace_id_key" ON "public"."project" ("workspace_id", "key")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_issue_project_id_number" ON "public"."issue" ("project_id", "number")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_label_project_id_name" ON "public"."label" ("project_id", "name")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_issue_link_source_issue_id_target_issue_id_type" ON "public"."issue_link" ("source_issue_id", "target_issue_id", "type")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_workflow_definition_project_id" ON "public"."workflow_definition" ("project_id")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_issue_watcher_issue_id_user_id" ON "public"."issue_watcher" ("issue_id", "user_id")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_webhook_endpoint_workspace_id_url" ON "public"."webhook_endpoint" ("workspace_id", "url")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_webhook_delivery_idempotency_key" ON "public"."webhook_delivery" ("idempotency_key")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "uq_bulk_operation_idempotency_key" ON "public"."bulk_operation" ("idempotency_key")`,
      `CREATE TABLE IF NOT EXISTS "public"."issue_labels" ("issue_id" INTEGER NOT NULL, "label_id" INTEGER NOT NULL, PRIMARY KEY ("issue_id", "label_id"))`,
      `ALTER TABLE "public"."issue_labels" ADD CONSTRAINT fk_issue_labels_44f3203f FOREIGN KEY ("issue_id") REFERENCES "public"."issue"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
      `ALTER TABLE "public"."issue_labels" ADD CONSTRAINT fk_issue_labels_d5d688ce FOREIGN KEY ("label_id") REFERENCES "public"."label"("id") ON DELETE CASCADE ON UPDATE CASCADE`
];

const POSTGRES_DOWN: string[] = [
      `DROP TABLE IF EXISTS "public"."issue_labels"`,
      `DROP TABLE IF EXISTS "public"."idempotency_key"`,
      `DROP TABLE IF EXISTS "public"."bulk_operation"`,
      `DROP TABLE IF EXISTS "public"."webhook_delivery"`,
      `DROP TABLE IF EXISTS "public"."webhook_endpoint"`,
      `DROP TABLE IF EXISTS "public"."notification"`,
      `DROP TABLE IF EXISTS "public"."issue_watcher"`,
      `DROP TABLE IF EXISTS "public"."workflow_transition"`,
      `DROP TABLE IF EXISTS "public"."workflow_definition"`,
      `DROP TABLE IF EXISTS "public"."saved_filter"`,
      `DROP TABLE IF EXISTS "public"."issue_link"`,
      `DROP TABLE IF EXISTS "public"."activity_log"`,
      `DROP TABLE IF EXISTS "public"."reaction"`,
      `DROP TABLE IF EXISTS "public"."comment_revision"`,
      `DROP TABLE IF EXISTS "public"."comment"`,
      `DROP TABLE IF EXISTS "public"."label"`,
      `DROP TABLE IF EXISTS "public"."issue"`,
      `DROP TABLE IF EXISTS "public"."sprint"`,
      `DROP TABLE IF EXISTS "public"."project"`,
      `DROP TABLE IF EXISTS "public"."membership"`,
      `DROP TABLE IF EXISTS "public"."user"`,
      `DROP TABLE IF EXISTS "public"."workspace"`
];

export class BaselineSchema_20260507133946 extends Migration {
  async up(ctx: MigrationContext): Promise<void> {
    const ddls = ctx.driver.isMySqlFamily() ? MYSQL_UP : POSTGRES_UP;
    for (const ddl of ddls) {
      await ctx.query(ddl);
    }
  }

  async down(ctx: MigrationContext): Promise<void> {
    const ddls = ctx.driver.isMySqlFamily() ? MYSQL_DOWN : POSTGRES_DOWN;
    for (const ddl of ddls) {
      await ctx.query(ddl);
    }
  }
}
